# Generated by Django 3.1.2 on 2020-11-25 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='when_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
