# Generated by Django 3.1.1 on 2020-09-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('imageurl', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('creator', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
