# Generated by Django 3.1.2 on 2020-11-25 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_when_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='when',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
