# Generated by Django 3.1.1 on 2020-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemcount',
            field=models.IntegerField(default=0),
        ),
    ]
