# Generated by Django 3.1.2 on 2020-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_color',
            field=models.CharField(default='#A52A2A', max_length=17),
        ),
    ]
