# Generated by Django 3.1.2 on 2020-11-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_user_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_color',
            field=models.CharField(max_length=17),
        ),
    ]
